#ifndef _SMARTRF_SETTINGS_PREDEFINED_H_
#define _SMARTRF_SETTINGS_PREDEFINED_H_


//*********************************************************************************
// Generated by SmartRF Studio version 2.11.0 (build #122)
// Tested for SimpleLink SDK version: CC13x0 SDK 2.30.xx.xx
// Device: CC1310 Rev. 2.1
//
//*********************************************************************************


#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_hs_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_hs_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_prop_cmd.h)

#include <ti/drivers/rf/RF.h>

/* TX Power Lookup Tables
 * 1. Power table for CC1310
 * 2. Power Table for CC1310 + CC1190 (US)
 * 3. Power Table for CC1310 + CC1190 (EU)
 */

// TX Power table size definition
#define RF_PROP_TX_POWER_TABLE_SIZE 17
#define RF_PROP_TX_POWER_TABLE_SIZE_REUS  10
#define RF_PROP_TX_POWER_TABLE_SIZE_REEU  8

 // TX Power Table Object
extern RF_TxPowerTable_Entry RF_PROP_txPowerTable[];
extern RF_TxPowerTable_Entry RF_PROP_txPowerTableREUS[];
extern RF_TxPowerTable_Entry RF_PROP_txPowerTableREEU[];

/* RF Core API commands */
/* RF command pointers for easylink */
extern RF_Mode RF_prop_fsk;
extern RF_Mode RF_prop_lrm;
extern RF_Mode RF_prop_ook;
extern RF_Mode RF_prop_hsm;
extern RF_Mode RF_prop_sl_lr;

extern rfc_CMD_PROP_RADIO_DIV_SETUP_t RF_cmdPropRadioDivSetup_fsk;
extern rfc_CMD_PROP_RADIO_DIV_SETUP_t RF_cmdPropRadioDivSetup_lrm;
extern rfc_CMD_PROP_RADIO_DIV_SETUP_t RF_cmdPropRadioDivSetup_ook;
extern rfc_CMD_RADIO_SETUP_t          RF_cmdRadioSetup_hsm;
extern rfc_CMD_PROP_RADIO_DIV_SETUP_t RF_cmdPropRadioDivSetup_sl_lr;

extern rfc_CMD_HS_TX_t RF_cmdTxHS;
extern rfc_CMD_HS_RX_t RF_cmdRxHS;
extern rfc_CMD_FS_t RF_cmdFs_preDef;
extern rfc_CMD_PROP_TX_t RF_cmdPropTx_preDef;
extern rfc_CMD_PROP_RX_ADV_t RF_cmdPropRxAdv_preDef;

extern uint32_t pOverrides_fsk[];
extern uint32_t pOverrides_lrm[];
extern uint32_t pOverrides_ook[];
extern uint32_t pOverrides_hsm[];
extern uint32_t pOverrides_sl_lr[];

#endif // _SMARTRF_SETTINGS_PREDEFINED_H_
